#!/usr/bin/env bash
set -o errexit
set -o pipefail

main() {
  local inst_name="${1:-nat-conntracker}"
  : "${RUNDIR:=/var/tmp/travis-run.d}"

  __loadenv

  : "${NAT_CONNTRACKER_CONNTRACK_ARGS:=-o%20xml%20-E%20conntrack}"
  : "${NAT_CONNTRACKER_SELF_IMAGE:-travisci/nat-conntracker:master}"

  local conntrack_args
  conntrack_args="$(__urlunquote "${NAT_CONNTRACKER_CONNTRACK_ARGS}")"
  local env_file="${RUNDIR}/nat-conntracker.env"
  printenv | grep ^NAT_CONNTRACKER | sort >"${env_file}"

  docker rm -f "${inst_name}" || true

  conntrack ${conntrack_args} |
    exec docker run \
      --rm \
      --user nobody \
      --interactive \
      --attach STDIN \
      --attach STDOUT \
      --attach STDERR \
      --name "${inst_name}" \
      --env-file "${env_file}" \
      "${NAT_CONNTRACKER_SELF_IMAGE}"
}

__loadenv() {
  : "${ETC_DEFAULT:=/etc/default}"

  for config_file in \
    nat-conntracker \
    nat-conntracker-cloud-init \
    nat-conntracker-local; do
    if [ -f "${ETC_DEFAULT}/${config_file}" ]; then
      set -o allexport
      source "${ETC_DEFAULT}/${config_file}"
      set +o allexport
    fi
  done
}

__urlunquote() {
  python3 <<EOPYTHON
import sys
import urllib.parse
sys.stdout.write(
    urllib.parse.unquote_plus("${1}") + '\\n'
)
EOPYTHON
}

main "$@"
