#!/usr/bin/env bash
set -o errexit
set -o pipefail

main() {
  set -o allexport
  eval "$(__loadenv)"
  set +o allexport
  local conntrack_args="${NAT_CONNTRACKER_CONNTRACK_ARGS}"
  if [[ ! "${conntrack_args}" ]]; then
    conntrack_args='-o xml -E conntrack'
  fi
  conntrack ${conntrack_args} | nat-conntracker -
}

__loadenv() {
  : "${ETC_DEFAULT:=/etc/default}"

  for config_file in \
    nat-conntracker \
    nat-conntracker-cloud-init \
    nat-conntracker-local; do
    if [ -f "${ETC_DEFAULT}/${config_file}" ]; then
      cat "${ETC_DEFAULT}/${config_file}"
    fi
  done
}

main "$@"
