language: python
sudo: required
python: '3.6'
cache:
  pip: true
services:
- redis-server
install: make deps
script:
- make lint
- make install
- make test
- make docker-build
- make docker-login
- make docker-push
after_success:
- codecov
notifications:
  email: false
