language: python
python:
- '2.7'
- '3.6'
install: make deps
script:
- make lint
- make install
- make test
- git ls-files '*.py' | xargs flake8
- python setup.py install
- pytest --cov=nat_conntracker tests/
